### ISSUE TITLE
Can we remove these margins?

### ISSUE THREAD

**Issue by almarklein** [plotly/dash-slicer#28]
When you zoom into a plot, a large part of the image is cut off, even though these is plenty of space. Can we fix that?

![afbeelding](https://user-images.githubusercontent.com/3015475/100627453-505dd580-3327-11eb-82e0-5573d8bab999.png)

**Comment by nicolaskruchten** [comment]
this is to maintain the square aspect ratio, right?

**Comment by almarklein** [comment]
I think so. My knowledge of how plotly does this figure layout is limited. I'd be happy to play and see if this can be improved. Hints are welcome :)

**Comment by almarklein** [comment]
Maybe some additional comment. When the figure loads, it is initialized to the full view. In this case the height is much larger than the width. Things look alright, but when you zoom in, the available horizontal space is not used. I would expect the image to be clipped at the figure boundaries, not at as shown above.

**Comment by almarklein** [comment]
Found it! `constrain="range",`
