### ISSUE TITLE
Add method to clear overlay data

### ISSUE THREAD

**Issue by emmanuelle** [plotly/dash-slicer#33]
At the moment it's possible to clear the overlay data of a slicer by passing an array or zeros but it would be faster to return a list of `None`. This occurred to me when updating the chest X-ray app where I had to use this mask of zeros to clear the overlay data.

**Comment by almarklein** [comment]
Good point! Would `slicer.create_overlay_data(None)` work for an API?

**Comment by emmanuelle** [comment]
Yes, this would be a good solution I think.
