### ISSUE TITLE
Annotation tool 

### ISSUE THREAD

**Issue by Subhashis-Banerjee** [plotly/dash-slicer#58]
Is it possible to interactively annotate slices of a volume in dash-slicer?

**Comment by almarklein** [comment]
Yes, see for example https://dash.gallery/dash-covid-xray/. Dash-slicer has support for masks, so you can visualize the data as well as an overlay. The interaction (how mouse clicks result in changes to the mask) are for you to implement.

**Comment by almarklein** [comment]
That's because of how that app works. It is not per-slice, but you select a rough volume. If you are writing an app yourself in which you want per-slice annotations, you need to eg. reset the drawing tool.
