### ISSUE TITLE
CI / CD / docs

### ISSUE THREAD

**Issue by almarklein** [plotly/dash-slicer#7]
* Github actions or CircleCI?
* What is the process for deploying the docs @ https://dash.plotly.com?

**Comment by emmanuelle** [comment]
The repo for the Dash docs is on https://github.com/plotly/dash-docs; changes to master are deployed automatically (to a Dash Enterprise instance). Branches of pull requests are deployed manually to heroku (see for example https://github.com/plotly/dash-docs/pull/1004). 

As for CI, CircleCI is probably more flexible if we want to test different versions of Python etc, what do you think?

**Comment by almarklein** [comment]
Ok, I think it's best to wait with writing docs in another repo until the API is somewhat stable.

I have good experiences with GH actions (also multiple Python versions and OS's, but it looks like CircleCI is used in all Plotly projects, so let's go with that for consistency :)

**Comment by emmanuelle** [comment]
Regarding GH Actions vs Circle CI, plotly people are also keen on experimenting and most large plotly projects were created before GH actions became really nice so feel free to choose whichever tool you prefer.

**Comment by almarklein** [comment]
CI done in #14. I suppose we can add an example to `dash-sample-apps` and call that a deploy?

**Comment by emmanuelle** [comment]
We could, or I could add a CircleCI config file and setup the deploy key for this repo so that one of the example apps would be deployed on every new commit to master (or other branches). Probably the latter solution is better because we would be able to detect regressions faster?

**Comment by almarklein** [comment]
> Probably the latter solution is better because we would be able to detect regressions faster?

That's a good point. That would be great!

**Comment by almarklein** [comment]
Docs are live now, closing!

**Comment by almarklein** [comment]
Let's add this to the readme
![afbeelding](https://user-images.githubusercontent.com/3015475/102207234-0c91d100-3ece-11eb-8a2b-6846a4281931.png)
