### ISSUE TITLE
Reduce noise in the callback graph

### ISSUE THREAD

**Issue by almarklein** [plotly/dash-slicer#9]
> [...] with the long id names, it's quite painful to look at the callback graph in the developer tools (which you can see with debug=True). This is not specific to this project, but it might be worth submitting a PR to Dash to represent long ids in a different format (see for example plotly/dash#1179 for the last modifications of the code generating the callback graph). 

In #4, the id's where changed to be dict id's, but these are very long e.g. when shown in the callback graph debugger tool. Some options (both are probably a good idea):
* Somehow display such id's more efficiently in the callback graph.
* Use only dict-id's for objects that need it.

**Comment by emmanuelle** [comment]
As a temporary fix, I just discovered (by reading the dash PR!) that it is possible to drag nodes of the callback graph so that labels do not collide.
